const ACCEPTED_WORDS = {
  en: [
    "accept",
    "agree",
    "ok",
    "got it",
    "i understand",
    "continue",
    "allow",
    "consent",
    "yes",
    "confirm",
  ],
  de: [
    "akzeptieren",
    "einverstanden",
    "verstanden",
    "fortfahren",
    "ok",
    "ja",
    "zustimmen",
    "erlauben",
    "bestätigen",
  ],
  fr: [
    "accepter",
    "j'accepte",
    "d'accord",
    "je comprends",
    "continuer",
    "ok",
    "oui",
    "permettre",
    "autoriser",
    "confirmer",
  ],
  es: [
    "aceptar",
    "de acuerdo",
    "entiendo",
    "continuar",
    "ok",
    "sí",
    "permitir",
    "autorizar",
    "confirmar",
  ],
  it: [
    "accetta",
    "accetto",
    "acconsento",
    "ho capito",
    "continua",
    "ok",
    "okay",
    "va bene",
    "consento",
    "consenti",
    "sì",
    "permetto",
    "confermo",
    "Consenti tutti i cookie",
  ],
  nl: [
    "accepteren",
    "akkoord",
    "ik begrijp het",
    "doorgaan",
    "ok",
    "ja",
    "toestaan",
    "bevestigen",
  ],
  pl: [
    "akceptuję",
    "zgadzam się",
    "rozumiem",
    "kontynuuj",
    "ok",
    "tak",
    "zezwalam",
    "potwierdzam",
  ],
  sv: ["godkänn", "jag förstår", "fortsätt", "ok", "ja", "tillåt", "bekräfta"],
  da: ["accepter", "jeg forstår", "fortsæt", "ok", "ja", "tillad", "bekræft"],
  fi: ["hyväksy", "ymmärrän", "jatka", "ok", "kyllä", "salli", "vahvista"],
  pt: [
    "aceitar",
    "concordo",
    "entendo",
    "continuar",
    "ok",
    "sim",
    "permitir",
    "confirmar",
  ],
  ru: [
    "принять",
    "согласен",
    "понимаю",
    "продолжить",
    "ок",
    "да",
    "разрешить",
    "подтвердить",
  ],
  zh: ["接受", "同意", "我明白", "继续", "好的", "是的", "允许", "确认"],
  ja: [
    "受け入れる",
    "同意する",
    "理解しました",
    "続ける",
    "OK",
    "はい",
    "許可する",
    "確認する",
  ],
  ko: [
    "수락",
    "동의",
    "이해했습니다",
    "계속",
    "확인",
    "네",
    "허용",
    "확인하다",
  ],
};

export { ACCEPTED_WORDS };
